{% set version = "1.10.4" %}
{% set sha256 = "562e617eac025f4247fe5b18cfa7177672c796f4ceaafb35672f917cf6c9a937" %}

package:
  name: python-blosc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blosc/blosc-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    # We can't use CMAKE_GENERATOR implicitly via conda_build_config.yaml, yet,
    # due to https://github.com/AnacondaRecipes/aggregate/pull/182
    - set "CMAKE_GENERATOR={{ CMAKE_GENERATOR }}"  # [win]
    - export DISABLE_BLOSC_SSE2=1  # [ppc64le]
    - export DISABLE_BLOSC_AVX2=1  # [ppc64le]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - pip
    - blosc
    - setuptools
    - wheel
    - scikit-build
  run:
    - python
    - blosc

test:
  requires:
    - numpy
    - psutil
  imports:
    - blosc
  commands:
    - python -c "import blosc; blosc.print_versions()"
    - python -c "import blosc; blosc.test()"

about:
  home: https://github.com/Blosc/python-blosc
  license_family: BSD
  license: BSD-3-Clause
  license_file:
    - LICENSES/PYTHON-BLOSC.txt
    - zstd-licenses.txt
  dev_url: https://github.com/Blosc/python-blosc
  doc_url: http://python-blosc.blosc.org/
  summary: A Python wrapper for the extremely fast Blosc compression library

extra:
  recipe-maintainers:
    - FrancescElies
