{% set version = "1.11.3" %}

package:
  name: python-blosc
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/blosc/blosc-{{ version }}.tar.gz
  sha256: 89ed658eba7814a92e89c44d8c524148d55921595bc133bd1a90f8888a9e088e

build:
  number: 0
  skip: true  # [py<39]
  script:
    - export USE_SYSTEM_BLOSC=1    # [unix]
    - set "USE_SYSTEM_BLOSC=1"     # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    # When cross-compiling scikit-build will link to libpython.dylib which results
    # in segfaults. Let's replace that with libc++
    - ${INSTALL_NAME_TOOL} -change @rpath/libpython${PY_VER}.dylib @rpath/libc++.1.dylib ${PREFIX}/lib/python${PY_VER}/site-packages/blosc/blosc_extension.cpython-{{ py }}-darwin.so   # [build_platform != target_platform and osx]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - pip
    - blosc
    - setuptools
    - wheel
    - scikit-build
  run:
    - python

test:
  requires:
    - pip
    - numpy
    - psutil
  imports:
    - blosc
  commands:
    - pip check
    - python -c "import blosc; blosc.print_versions()"
    - python -c "import blosc; blosc.test()"

about:
  home: https://github.com/Blosc/python-blosc
  license_family: BSD
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
  dev_url: https://github.com/Blosc/python-blosc
  doc_url: http://python-blosc.blosc.org/
  summary: A Python wrapper for the extremely fast Blosc compression library

extra:
  recipe-maintainers:
    - FrancescElies
    - ocefpaf
