{% set name = "blosc" %}
{% set version = "1.7.0" %}
{% set sha256 = "7ffa7d243a980f5d9e63d7a1f8934803d986398f0aec058345095e47f0cabc72" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script:
    - "{{ PYTHON }} -m pip install . -vv --install-option=--blosc=\"$PREFIX\""  # [unix]
    - "{{ PYTHON }} -m pip install . -vv --install-option=--blosc=\"%LIBRARY_BIN%\""  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - blosc
  run:
    - python
    - blosc
    - numpy

test:
  imports:
    - blosc
  commands:
    - python -c "import blosc; blosc.print_versions()"
    - python -c "import blosc; blosc.test()"

about:
  home: https://github.com/Blosc/python-blosc
  license_family: Apache
  license: Apache 2.0
  license_file: LICENSES/PYTHON-BLOSC.txt
  summary: 'A Python wrapper for the extremely fast Blosc compression library'

extra:
  recipe-maintainers:
    - danielfrg
    - FrancescElies
    - beckermr
