{% set name = "blosc" %}
{% set version = "1.6.2" %}
{% set sha256 = "8113aaf6b3a2c16147d392231e3e10a8193d5ddd6efc44d8df2466d1dc53fbb8" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --blosc=$PREFIX --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - blosc
  run:
    - python
    - blosc
    - numpy

test:
  imports:
    - blosc
  commands:
    - python -c "import blosc; blosc.print_versions()"
    - python -c "import blosc; blosc.test()"

about:
  home: https://github.com/Blosc/python-blosc
  license_family: Apache
  license: Apache 2.0
  license_file: LICENSES/PYTHON-BLOSC.txt
  summary: 'A Python wrapper for the extremely fast Blosc compression library'

extra:
  recipe-maintainers:
    - danielfrg
    - FrancescElies
