{% set name = "blosc" %}
{% set version = "1.5.1" %}
{% set sha256 = "5c16d39ea7baa5b4f726e1bb06869356c5f8564988e85585a23e0c920d0ba9b2" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --blosc=$PREFIX --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - blosc
  run:
    - python
    - blosc
    - numpy

test:
  imports:
    - blosc
  commands:
    - python -c "import blosc; blosc.print_versions()"
    - python -c "import blosc; blosc.test()"

about:
  home: https://github.com/Blosc/python-blosc
  license_family: Apache
  license: Apache 2.0
  license_file: LICENSES/PYTHON-BLOSC.txt
  summary: 'A Python wrapper for the extremely fast Blosc compression library'

extra:
  recipe-maintainers:
    - danielfrg
    - FrancescElies
