appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: ILWlUdN0Da1PG5B95ayrlsjdnR49IVsh+W3Zz5ML7Mi1VkZiTAUVKPt00FthdG/i5pDz6XxO8C6tvEe2n/3tRKq6fZaKjm6UmvHMHHD3m63aJUlFsoOgoWSFvzpRJXkRA6/Jal2ARzwfw+u3+M8a4BDWp9CtTM+nLYwEJTVPGA8vV6mZlsE7SnxgNKvfJ71/ZD7CgXIDJpks7NAn/vY+7JqRRi7symn/CdfaN6w7PQ8H5U6JyIv+1x1bEV++eVb/SWMzzk7lIuw4YzWOWuPsgUgZtzYqE57lMxS9I/8U2/OcDdslpqiUEVmDXQY5+RqERufN2zpsMPfvGkDpr90dQb2xDUdDeHhXUPKdNIOgT/DMbAk7Fja56m6LSHyZ+pDGyNwNiOn4D5TYeQuk82k19tu1tJHyJ+PBPH5KhIddUwjC/4cylOE3H4/W68kprHnZ+OP2rzEG+NhV4JVbEPomVrsh5OwmZcak0hRpeC4o/HUY6Lc1zt28ZeYmYYmzhsM7Yjfvx/e7/JUX8gqPf53dMKvBjq2x0tN5prSQ3lg6YRlNMuBHfFT/81zO+u53lTMzOecB3LISntv1XOxcm/J7pBCc/J+5rcggVi9daY28P0fwd9AwnTP4wQcCiKgN8FUUkl3C4LEi4NmRUhNCtZwPeXy8dYqBzoz4H9JtynO091E=}
provider:
  win: azure
bot:
  automerge: true
